{
  "hash": "d42281882a3af094c56f2b64d417dcc5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Google Analytics\"\nsubtitle: \"Website performance analysis using GA4\"\nformat:\n  html:\n    code-fold: true\n    code-tools: false\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n## GA4 Overview\n\nGoogle Analytics 4 was used to review website engagement, event activity, page performance, traffic behavior, and revenue-related performance. The screenshots below show the GA4 Engagement Overview and Events reports for the last 28 days.\n\n---\n\n## GA4 Report Screenshots\n\n![](images/ga4-events-report.png)\n\n![](images/ga4-engagement-overview.png)\n\n---\n\n## Key Metrics Summary\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|metric                                  |value                |\n|:---------------------------------------|:--------------------|\n|Date range                              |Jun 10 – Jul 7, 2026 |\n|Total users                             |88,573               |\n|Total event count                       |1,302,922            |\n|Event count per active user             |15.41                |\n|Total revenue                           |$178,423.24          |\n|Views                                   |336K                 |\n|Average engagement time per active user |54 seconds           |\n|Engaged sessions per active user        |0.51                 |\n|Average engagement time                 |43 seconds           |\n|Active users in last 30 minutes         |76                   |\n\n\n:::\n:::\n\n\n---\n\n## Top Events by Event Count\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](google-analytics_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Event Count per Active User\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](google-analytics_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Top Pages by Views\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](google-analytics_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Active Users in Last 30 Minutes\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](google-analytics_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Business Insight\n\n- The site had **88,573 total users** and **1,302,922 total events** during the last 28 days.\n- The strongest event categories were **page_view** and **view_item_list**.\n- The **Home** page had the highest visible page views.\n- Engagement was moderate, with **54 seconds average engagement time per active user** and **0.51 engaged sessions per active user**.\n\n---\n\n## Skills Demonstrated\n\n- Google Analytics 4\n- Website performance analysis\n- Data visualization\n- Marketing analytics\n- Business insight\n- Quarto website development",
    "supporting": [
      "google-analytics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}